version: '3.4'

services:
  kindrobots:
    image: kind/robots@latest
    build:
      context: .output/server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3333
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
